ARG NODE_VERSION=24.11.1-alpine

FROM node:${NODE_VERSION} AS BASE

WORKDIR /app

COPY package*.json ./

#download dependencies
RUN npm ci

#copy code
COPY . .

RUN npm run build

# EXPOSE port
EXPOSE 3000

#run commands
CMD ["node", "dist/index.js"]