// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { ENV } from "./src/utils/env";
import { defineConfig } from "prisma/config";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: ENV.POSTGRES_URL,
  },
});
